server.port=8080
##rver.address=0.0.0.0

# MONGODB - Uses env variable in production, falls back to local
spring.data.mongodb.uri="mongodb+srv://jayasundarakgkgd22_db_user:<AipwrckRPp2AtXau>@cluster0.smp2vdy.mongodb.net/?appName=Cluster0";
spring.data.mongodb.database=restrosync

# App
spring.application.name=RestroSync Backend

# CORS - Uses env variable in production, falls back to local
cors.allowed-origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:5174}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true

# Cloudinary
cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME:dt0bdj2xg}
cloudinary.api.key=${CLOUDINARY_API_KEY:732394989442132}
cloudinary.api.secret=${CLOUDINARY_API_SECRET:cNZ2t6F9wXhwh1EpT_LyqbPZNDQ}