server.port=8080

# LOCAL MONGODB
spring.data.mongodb.uri=mongodb://localhost:27017/restrosync
spring.data.mongodb.database=restrosync

# App
spring.application.name=RestroSync Backend


# application.properties
cors.allowed-origins=http://localhost:5173,http://localhost:5174
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true