server.port=8080

# LOCAL MONGODB
spring.data.mongodb.uri=mongodb://localhost:27017/restrosync
spring.data.mongodb.database=restrosync

# App
spring.application.name=RestroSync Backend

# CORS
cors.allowed-origins=http://localhost:5173